name: API CI

on:
  push:
    branches:
      - main
      - develop
      - tests
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches:
      - main
      - develop
      - tests
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/api-ci.yml'

defaults:
  run:
    working-directory: .

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  unit-integration-tests:
    runs-on: ubuntu-latest
    env:
      ACCESS_SECRET: test-secret
      ACCESS_EXPIRES_IN: 60m
      ROUNDS_HASH_PASSWORD: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: install dependencies
        run: npm ci
      - name: run unit and integration tests
        run: npm run test

  e2e:
    runs-on: ubuntu-latest
    env:
      # DB configuration
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      # App configuration
      ROUNDS_HASH_PASSWORD: 10
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      ACCESS_EXPIRES_IN: ${{ secrets.ACCESS_EXPIRES_IN }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
      REFRESH_EXPIRES_IN: ${{ secrets.REFRESH_EXPIRES_IN }}

    services:
      mysql-e2e:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install MySQL client (needed for mysqladmin/mysql CLI)
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Init database
        run: npm run migrations:run:test

      - name: Run E2E tests
        run: npm run test:e2e
